# layout -- 布局相关
# language: zh-CN

##menu 导航菜单显示
menu:
- page: 首页
  url: /
  icon: fa-home
- page: UBC
  url: /categories/UBC/
  icon: 
- page: 夏令营
  url: /categories/夏令营/
  icon:
- page: 餐饮
  url: /categories/餐饮/
  icon: 
- page: 购物
  url: /categories/购物/
  icon:
- page: 室外游乐场
  url: /categories/室外游乐场/
  icon:


## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml

## 通用时间格式化
date_format: YYYY-MM-DD HH:mm:ss

## widgets
widgets:
- notification
- social
- category
- archive
- tagcloud
- friends

# 各个小工具的设置

## 网站公告设置
notification: |-
            <p>欢迎大家咨询
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/shenliyang
 - name: 邮箱
   icon: envelope-o
   href: mailto:snippet@91h5.cc
 - name: 联系QQ
   icon: qq
   href: /
 - name: 微博
   icon: weibo
   href: /
 - name: QQ群
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 彩色标签云设置
tagcloud_config:
   min_font: 1
   max_font: 1
   unit: em
   amount: 100
   color: true
   orderby: 'count'

## 友链设置
links:
  - 卓逸天成: http://www.skight.com
  - Skight I-Tech Inc.: http://www.skight.ca
  - 予沁安: http://my.oschina.net/wonner


# 自定义内容设置

## 添加版权保护 
archiveCopyright:
  enable: true
  tip: '商业转载请联系作者获得授权,非商业转载请注明出处 © skight.ca'


## 当无目录时的显示文字，默认为'无'
noCategoryText: '无'

## 过低版本的浏览器提醒文字
outdated_browser_text: '你使用的浏览器版本过低，为了你更好的阅读体验，请更新浏览器的版本或者使用其他现代浏览器，比如Chrome、Firefox、Safari等。'

## 文章过期提醒功能
warning:
  days: 300 
  text: '本文于%d天之前发表，文中内容可能已经过时。'


## 首页文章简介的图片占位符
placeholder: ./img/loading.gif

## 首页文章简介的图片
defaultImgs:
  - 

### 截取文章首页描述字数
excerptLength: 120

## 代码高亮配置
highlightTheme: default


## 版权声明文字，支持html/text，但不要使用<li>标签
cc: |-
      技术支持：<a href="http://www.skight.ca" target="_blank">
       Skight I-Tech Inc.
      </a>


## 主题评论
### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10


###友言评论
uyan:
  enable: true
  uyan_id: 1966422


## 网盟CNZZ网站统计
cnzz_anaylytics:

## 百度网站统计
baidu_anaylytics: 

## 百度文章推送
baidu_push:

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

#网站主题配置
since: 2017
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all，搜索 `meta name="robots"` 或请参考： https://support.google.com/webmasters/answer/79812?hl=zh-Hans
version: 1.1.0
